"""Tests for execution waterfall, tree, details inspection, and CLI node debug commands."""

from datetime import datetime, timezone
import json
from pathlib import Path
from typer.testing import CliRunner

from cz.cli.main import app
from cz.execution.models import Execution, Span
from cz.execution.sqlite import SQLiteExecutionStore
from cz.formatters.viewer import generate_execution_viewer_html

runner = CliRunner()


def test_cli_waterfall_and_details_and_node_debug(tmp_path: Path):
    cohzen_dir = tmp_path / ".cohzen"
    cohzen_dir.mkdir(parents=True, exist_ok=True)
    db_path = cohzen_dir / "executions.db"
    store = SQLiteExecutionStore(db_path=db_path)

    # Create dummy app file with a node
    app_file = tmp_path / "app.py"
    app_file.write_text(
        "def planner(state: dict) -> dict:\n"
        "    return {'plan': 'Plan for ' + state.get('inquiry', '')}\n",
        encoding="utf-8",
    )

    now = datetime(2026, 10, 2, 12, 0, 0, tzinfo=timezone.utc)
    ex = Execution(id="ex_test_99", graph_id="demo_graph", status="completed", started_at=now, duration_ms=250.0)
    store.create_execution(ex)

    span1 = Span(
        id="sp_planner",
        execution_id="ex_test_99",
        kind="node",
        name="planner",
        status="completed",
        started_at=now,
        duration_ms=100.0,
        input={"inquiry": "test query"},
        output={"plan": "Plan for test query"},
        reason="Analyzing test input",
    )
    store.create_span(span1)

    # 1. Test `cz waterfall <id>`
    res_wf = runner.invoke(app, ["waterfall", "ex_test_99", "--path", str(tmp_path)])
    assert res_wf.exit_code == 0
    assert "Execution Waterfall" in res_wf.stdout
    assert "planner" in res_wf.stdout

    # 2. Test `cz run <id> --details`
    res_det = runner.invoke(app, ["run", "ex_test_99", "--path", str(tmp_path), "--details"])
    assert res_det.exit_code == 0
    assert "Execution Details & Captured Context" in res_det.stdout
    assert "Input State" in res_det.stdout
    assert "Output State" in res_det.stdout
    assert "Analyzing test input" in res_det.stdout

    # 3. Test `cz node run planner --from-run <id>`
    res_node = runner.invoke(app, ["node", "run", "planner", "--from-run", "ex_test_99", "--path", str(tmp_path)])
    assert res_node.exit_code == 0
    assert "Running Isolated Node" in res_node.stdout
    assert "planner" in res_node.stdout
    assert "Output Generated by planner" in res_node.stdout
    assert "Plan for test query" in res_node.stdout

    # 4. Test HTML visualizer generation
    spans = store.get_spans("ex_test_99")
    html = generate_execution_viewer_html(ex, spans)
    assert "Execution Waterfall & Trace: ex_test_99" in html
    assert "demo_graph" in html
    assert "planner" in html
