"""Command-line interface for Cohzen (cz)."""

from __future__ import annotations

from enum import Enum
import json
from pathlib import Path
import re
import shutil
from typing import Optional

import typer
from rich.console import Console

from cz import __version__
from cz.execution.debugger import get_node_input_from_run, resolve_node_function, run_isolated_node
from cz.execution.sqlite import SQLiteExecutionStore
from cz.formatters.console import print_audit_report, print_console_report
from cz.formatters.execution_fmt import (
    format_duration,
    format_status_icon,
    print_execution_detail,
    print_execution_details,
    print_execution_tree,
    print_execution_waterfall,
    print_executions_table,
)
from cz.formatters.json_fmt import format_json
from cz.formatters.mermaid import format_mermaid
from cz.formatters.viewer import open_execution_in_browser
from cz.scanner.engine import scan_repository

app = typer.Typer(
    name="cz",
    help="cz - Static LangGraph scanner and runtime execution tracking engine.",
    add_completion=False,
)
console = Console()


class OutputFormat(str, Enum):
    TABLE = "table"
    JSON = "json"
    MERMAID = "mermaid"


def _find_db(path_str: str) -> Path:
    p = Path(path_str).resolve()
    if p.is_file() and p.name == "executions.db":
        return p
    if (p / ".cohzen" / "executions.db").is_file():
        return p / ".cohzen" / "executions.db"
    for parent in [p, *p.parents]:
        cand = parent / ".cohzen" / "executions.db"
        if cand.is_file():
            return cand
    return p / ".cohzen" / "executions.db"


@app.command(name="init")
def init(
    path: str = typer.Argument(
        ".",
        help="Path to repository or project to initialize (defaults to current directory)",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Force re-initialization and overwrite existing manifest",
    ),
) -> None:
    """Initialize Cohzen in a project: generate static manifest, create local telemetry store, and enable auto-recording."""
    project_dir = Path(path).resolve()
    cohzen_dir = project_dir / ".cohzen"
    manifest_path = cohzen_dir / "manifest.json"
    db_path = cohzen_dir / "executions.db"

    if manifest_path.is_file() and not force:
        console.print(f"[yellow]Cohzen already initialized at {project_dir}[/yellow]")
        console.print("[dim]Use --force to re-scan architecture and overwrite manifest.[/dim]")
        return

    cohzen_dir.mkdir(parents=True, exist_ok=True)

    with console.status(f"[bold cyan]Scanning repository architecture at {project_dir}...[/bold cyan]"):
        result = scan_repository(str(project_dir))

    manifest_json = format_json(result)
    manifest_path.write_text(manifest_json, encoding="utf-8")

    # Initialize SQLite store
    SQLiteExecutionStore(db_path=db_path)

    # Add .cohzen/ to .gitignore
    gitignore_path = project_dir / ".gitignore"
    git_dir = project_dir / ".git"
    if gitignore_path.exists() or git_dir.exists():
        current_content = gitignore_path.read_text(encoding="utf-8") if gitignore_path.exists() else ""
        if ".cohzen" not in current_content:
            with open(gitignore_path, "a", encoding="utf-8") as f:
                if current_content and not current_content.endswith("\n"):
                    f.write("\n")
                f.write("# Cohzen execution telemetry\n.cohzen/\n")

    # Create sitecustomize.py for zero-effort auto-instrumentation
    sitecustomize_path = project_dir / "sitecustomize.py"
    hook_code = (
        "# Cohzen auto-instrumentation hook (generated by cz init)\n"
        "try:\n"
        "    import cz.execution\n"
        "    cz.execution.install()\n"
        "except Exception:\n"
        "    pass\n"
    )
    if not sitecustomize_path.exists():
        sitecustomize_path.write_text(hook_code, encoding="utf-8")
    else:
        existing = sitecustomize_path.read_text(encoding="utf-8")
        if "cz.execution" not in existing:
            with open(sitecustomize_path, "a", encoding="utf-8") as f:
                f.write(f"\n{hook_code}")

    # Install cohzen.pth into active venv site-packages if present
    for candidate in [project_dir, *project_dir.parents]:
        for sp in candidate.glob(".venv/lib/python*/site-packages"):
            try:
                (sp / "cohzen.pth").write_text("import cz.execution; cz.execution.install()\n", encoding="utf-8")
            except Exception:
                pass

    # Invoke scan and audit reports
    print_console_report(result, console=console)
    print_audit_report(result, console=console)

    console.print(f"\n[bold green]✔ Cohzen initialized at {project_dir}[/bold green]")
    console.print(
        f"  • Manifest: [cyan].cohzen/manifest.json[/cyan] ({result.total_graphs} graphs, {result.total_nodes} nodes, {len(result.tool_definitions)} tools)"
    )
    console.print("  • Telemetry DB: [cyan].cohzen/executions.db[/cyan]")
    console.print("  • Auto-recording: [cyan]sitecustomize.py[/cyan]")
    console.print("  • Added [cyan].cohzen/[/cyan] to [cyan].gitignore[/cyan]")
    console.print("\n[dim]Run your application normally:[/dim]")
    console.print("  [bold]python app.py[/bold]")
    console.print("\n[dim]Then inspect recorded executions:[/dim]")
    console.print("  [bold]cz runs[/bold]\n")


@app.command(name="deinit")
def deinit(
    path: str = typer.Argument(
        ".",
        help="Path to repository or project to deinitialize (defaults to current directory)",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Force de-initialization without confirmation",
    ),
) -> None:
    """Deinitialize Cohzen in a project: delete all changes made by the cz init command."""
    project_dir = Path(path).resolve()
    removed_items: list[str] = []

    # 1. Remove .cohzen directory
    cohzen_dir = project_dir / ".cohzen"
    if cohzen_dir.exists():
        if cohzen_dir.is_dir():
            shutil.rmtree(cohzen_dir)
        else:
            cohzen_dir.unlink()
        removed_items.append("Removed [cyan].cohzen/[/cyan] directory")

    # 2. Clean sitecustomize.py
    sitecustomize_path = project_dir / "sitecustomize.py"
    if sitecustomize_path.is_file():
        content = sitecustomize_path.read_text(encoding="utf-8")
        if "cz.execution" in content or "Cohzen auto-instrumentation hook" in content:
            cleaned = re.sub(
                r"\n?# Cohzen auto-instrumentation hook \(generated by cz init\)\n"
                r"try:\n"
                r"    import cz\.execution\n"
                r"    cz\.execution\.install\(\)\n"
                r"except Exception:\n"
                r"    pass\n?",
                "",
                content,
            )
            if "cz.execution" in cleaned:
                cleaned = re.sub(
                    r"\n?try:\s*\n\s*import cz\.execution\s*\n\s*cz\.execution\.install\(\)\s*\nexcept Exception:\s*\n\s*pass\n?",
                    "",
                    cleaned,
                )
            if not cleaned.strip():
                sitecustomize_path.unlink()
                removed_items.append("Removed [cyan]sitecustomize.py[/cyan]")
            else:
                sitecustomize_path.write_text(cleaned.strip() + "\n", encoding="utf-8")
                removed_items.append("Removed auto-recording hook from [cyan]sitecustomize.py[/cyan]")

    # 3. Clean .gitignore
    gitignore_path = project_dir / ".gitignore"
    if gitignore_path.is_file():
        content = gitignore_path.read_text(encoding="utf-8")
        if ".cohzen" in content:
            lines = content.splitlines()
            new_lines = []
            for line in lines:
                stripped = line.strip()
                if stripped == "# Cohzen execution telemetry":
                    continue
                if stripped in (".cohzen", ".cohzen/", "/.cohzen", "/.cohzen/"):
                    continue
                new_lines.append(line)

            cleaned = "\n".join(new_lines).strip()
            if not cleaned:
                gitignore_path.unlink()
                removed_items.append("Removed [cyan].gitignore[/cyan]")
            else:
                gitignore_path.write_text(cleaned + "\n", encoding="utf-8")
                removed_items.append("Removed [cyan].cohzen/[/cyan] from [cyan].gitignore[/cyan]")

    # 4. Remove cohzen.pth from virtualenv site-packages
    pth_removed = False
    for candidate in [project_dir, *project_dir.parents]:
        for pattern in [
            ".venv/lib/python*/site-packages/cohzen.pth",
            ".venv/Lib/site-packages/cohzen.pth",
            "venv/lib/python*/site-packages/cohzen.pth",
            "venv/Lib/site-packages/cohzen.pth",
        ]:
            for pth in candidate.glob(pattern):
                try:
                    if pth.is_file():
                        pth.unlink()
                        pth_removed = True
                except Exception:
                    pass
    if pth_removed:
        removed_items.append("Removed [cyan]cohzen.pth[/cyan] from virtual environment")

    if not removed_items:
        console.print(f"[yellow]No Cohzen initialization found at {project_dir}[/yellow]")
        return

    console.print(f"\n[bold green]✔ Cohzen deinitialized at {project_dir}[/bold green]")
    for item in removed_items:
        console.print(f"  • {item}")
    console.print()


@app.command(name="runs")
def list_runs(
    path: str = typer.Argument(
        ".",
        help="Path to repository or directory containing .cohzen (defaults to current directory)",
    ),
    limit: int = typer.Option(
        50,
        "--limit",
        "-n",
        help="Maximum number of executions to list",
    ),
    json_output_flag: bool = typer.Option(
        False,
        "--json",
        help="Output executions as JSON",
    ),
) -> None:
    """List recorded graph executions."""
    db_path = _find_db(path)
    if not db_path.is_file():
        console.print("[yellow]No execution store found.[/yellow]")
        console.print(f"[dim]Expected database at: {db_path}[/dim]")
        console.print("[dim]Run [bold]cz init[/bold] to initialize Cohzen for this project.[/dim]")
        return

    store = SQLiteExecutionStore(db_path=db_path)
    executions = store.list_executions(limit=limit)

    if json_output_flag:
        data = [e.model_dump(mode="json") for e in executions]
        print(json.dumps(data, indent=2, default=str))
    else:
        print_executions_table(executions, console=console)


@app.command(name="run")
def view_run(
    execution_id: str = typer.Argument(
        ...,
        help="Execution ID or prefix (e.g. a82f91)",
    ),
    path: str = typer.Option(
        ".",
        "--path",
        "-p",
        help="Path to repository or directory containing .cohzen",
    ),
    json_output_flag: bool = typer.Option(
        False,
        "--json",
        help="Output execution details and spans as JSON",
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="Display full inputs, outputs, prompts, LLMs, and tools",
    ),
    details: bool = typer.Option(
        False,
        "--details",
        "-d",
        help="Deep-dive inspection showing full inputs, outputs, prompts, LLMs, and tools",
    ),
    waterfall: bool = typer.Option(
        True,
        "--waterfall/--no-waterfall",
        "-w",
        help="Display timeline waterfall chart",
    ),
    tree: bool = typer.Option(
        True,
        "--tree/--no-tree",
        "-t",
        help="Display hierarchical execution tree",
    ),
    node: Optional[str] = typer.Option(
        None,
        "--node",
        help="Inspect only a specific node name",
    ),
    view: bool = typer.Option(
        False,
        "--view",
        help="Open interactive execution waterfall and trace visualizer in browser",
    ),
) -> None:
    """View detailed execution flow, timeline waterfall, spans, and metrics for a specific run."""
    db_path = _find_db(path)
    if not db_path.is_file():
        console.print(f"[bold red]Error:[/bold red] No execution store found at {db_path}")
        return

    store = SQLiteExecutionStore(db_path=db_path)
    execution = store.get_execution(execution_id)
    if not execution:
        console.print(f"[bold red]Error:[/bold red] Execution [yellow]{execution_id}[/yellow] not found in store.")
        return

    spans = store.get_spans(execution.id)

    if view:
        viewer_path = open_execution_in_browser(execution, spans)
        console.print(f"[bold green]✔ Opened execution trace and waterfall in browser ({viewer_path})[/bold green]")
        return

    if json_output_flag:
        data = {
            "execution": execution.model_dump(mode="json"),
            "spans": [s.model_dump(mode="json") for s in spans],
        }
        print(json.dumps(data, indent=2, default=str))
    else:
        print_execution_detail(
            execution,
            spans,
            console=console,
            verbose=verbose,
            show_waterfall=waterfall,
            show_tree=tree,
            show_details=details or verbose,
            node_filter=node,
        )


@app.command(name="waterfall")
def view_waterfall_cmd(
    execution_id: str = typer.Argument(
        ...,
        help="Execution ID or prefix (e.g. a82f91)",
    ),
    path: str = typer.Option(
        ".",
        "--path",
        "-p",
        help="Path to repository or directory containing .cohzen",
    ),
    view: bool = typer.Option(
        False,
        "--view",
        help="Open interactive execution waterfall in browser",
    ),
) -> None:
    """View the execution timeline waterfall chart for a specific run."""
    db_path = _find_db(path)
    if not db_path.is_file():
        console.print(f"[bold red]Error:[/bold red] No execution store found at {db_path}")
        return

    store = SQLiteExecutionStore(db_path=db_path)
    execution = store.get_execution(execution_id)
    if not execution:
        console.print(f"[bold red]Error:[/bold red] Execution [yellow]{execution_id}[/yellow] not found in store.")
        return

    spans = store.get_spans(execution.id)

    if view:
        viewer_path = open_execution_in_browser(execution, spans)
        console.print(f"[bold green]✔ Opened execution waterfall in browser ({viewer_path})[/bold green]")
    else:
        print_execution_waterfall(execution, spans, console=console)


node_app = typer.Typer(
    name="node",
    help="Test and debug individual LangGraph nodes in isolation.",
    add_completion=False,
)
app.add_typer(node_app, name="node")


@node_app.command(name="list")
def list_nodes_cmd(
    path: str = typer.Argument(
        ".",
        help="Path to repository or project (defaults to current directory)",
    ),
) -> None:
    """List all detected graph nodes and handlers across the project."""
    from rich import box
    from rich.table import Table

    project_dir = Path(path).resolve()
    with console.status(f"[bold cyan]Scanning nodes in {project_dir}...[/bold cyan]"):
        result = scan_repository(str(project_dir))

    nodes_seen = set()
    rows = []
    for g in result.graphs:
        for n in g.nodes:
            key = (g.graph_var, n.name)
            if key not in nodes_seen:
                nodes_seen.add(key)
                rel_file = Path(n.file_path).name
                llm_calls = len(n.agent_def.llm_calls) if n.agent_def else 0
                tools = len(n.agent_def.tools_bound) if n.agent_def else (len(n.tool_node_def.tools) if n.tool_node_def else 0)
                rows.append((g.graph_var, n.name, n.handler, f"{rel_file}:{n.line_number}", str(llm_calls), str(tools)))

    if not rows:
        console.print("[yellow]No LangGraph nodes detected in this project.[/yellow]")
        return

    t = Table(box=box.SIMPLE, show_header=True, header_style="bold dim")
    t.add_column("Graph", style="dim")
    t.add_column("Node Name", style="bold cyan")
    t.add_column("Handler", style="white")
    t.add_column("Location", style="dim")
    t.add_column("LLMs", justify="center", style="magenta")
    t.add_column("Tools", justify="center", style="yellow")

    for r in rows:
        t.add_row(*r)

    console.print(f"\n[bold white]Detected Nodes ({len(rows)})[/bold white]\n")
    console.print(t)
    console.print("\n[dim]Run any node in isolation with:[/dim]")
    console.print("  [bold]cz node run <node-name> --input '{\"key\": \"value\"}'[/bold]")
    console.print("  [bold]cz node run <node-name> --from-run <execution-id>[/bold]\n")


@node_app.command(name="run")
@app.command(name="debug")
def run_node_cmd(
    node_name: str = typer.Argument(
        ...,
        help="Name of the node to execute in isolation (e.g. planner, search, writer, verify_information)",
    ),
    from_run: Optional[str] = typer.Option(
        None,
        "--from-run",
        "-r",
        help="Execution ID from which to pull the exact captured input state",
    ),
    input_str: Optional[str] = typer.Option(
        None,
        "--input",
        "-i",
        help="JSON string representing the input state payload",
    ),
    input_file: Optional[Path] = typer.Option(
        None,
        "--input-file",
        "-f",
        help="Path to JSON file containing the input state payload",
    ),
    graph: Optional[str] = typer.Option(
        None,
        "--graph",
        "-g",
        help="Target python file or compiled graph reference (e.g. app.py or app.py:app)",
    ),
    path: str = typer.Option(
        ".",
        "--path",
        "-p",
        help="Project directory containing the node and .cohzen store",
    ),
    no_record: bool = typer.Option(
        False,
        "--no-record",
        help="Do not save this isolated debug run into Cohzen executions store",
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="Show verbose output with full input/output structures",
    ),
) -> None:
    """Execute a single graph node directly in isolation with custom or recorded inputs."""
    project_dir = Path(path).resolve()
    db_path = _find_db(str(project_dir))

    # Resolve input state
    input_state: Any = None
    if from_run:
        try:
            input_state = get_node_input_from_run(from_run, node_name, db_path=db_path)
            console.print(f"[dim]Loaded captured input for node [bold cyan]{node_name}[/bold cyan] from execution [bold]{from_run}[/bold][/dim]")
        except Exception as e:
            console.print(f"[bold red]Error fetching input from run {from_run}:[/bold red] {e}")
            return
    elif input_file:
        if not input_file.is_file():
            console.print(f"[bold red]Error:[/bold red] Input file {input_file} not found.")
            return
        try:
            input_state = json.loads(input_file.read_text(encoding="utf-8"))
        except Exception as e:
            console.print(f"[bold red]Error parsing JSON from {input_file}:[/bold red] {e}")
            return
    elif input_str:
        try:
            input_state = json.loads(input_str)
        except json.JSONDecodeError:
            input_state = input_str
    else:
        input_state = {}

    console.print(f"\n[bold white]Running Isolated Node:[/bold white] [bold cyan]{node_name}[/bold cyan]")
    console.print(f"[dim]Executing handler directly without running the complete graph...[/dim]\n")

    res = run_isolated_node(
        node_name=node_name,
        input_state=input_state,
        project_dir=project_dir,
        graph_target=graph,
        record=not no_record,
    )

    # Render results
    status_icon = "[bold green]✓ COMPLETED[/bold green]" if res.status == "completed" else "[bold red]✗ FAILED[/bold red]"
    console.print(f"Status:   {status_icon}")
    console.print(f"Duration: [bold cyan]{res.duration_ms:.1f}ms[/bold cyan]")
    if res.handler_name:
        console.print(f"Handler:  [dim]{res.handler_name} ({Path(res.file_path).name if res.file_path else ''})[/dim]")
    if res.execution_id and not no_record:
        console.print(f"Run ID:   [dim]{res.execution_id} (recorded)[/dim]")
    if res.reason:
        console.print(f"Why:      [italic cyan]{res.reason}[/italic cyan]")
    if res.error:
        console.print(f"[bold red]Error:[/bold red]    {res.error}")

    from rich.panel import Panel
    from rich.json import JSON

    # Print Input
    input_formatted = JSON(json.dumps(res.input_state, indent=2, default=str)) if isinstance(res.input_state, (dict, list)) else str(res.input_state)
    console.print(Panel(input_formatted, title=f"[bold]📥 Input Passed to {node_name}[/bold]", border_style="cyan"))

    # Print Output
    if res.output_state is not None:
        output_formatted = JSON(json.dumps(res.output_state, indent=2, default=str)) if isinstance(res.output_state, (dict, list)) else str(res.output_state)
        console.print(Panel(output_formatted, title=f"[bold]📤 Output Generated by {node_name}[/bold]", border_style="green"))

    # Print child spans if any
    if res.child_spans:
        console.print(f"\n[bold dim]Internal Operations ({len(res.child_spans)}):[/bold dim]")
        for sp in res.child_spans:
            kind_badge = f"[{sp.kind.upper()}]"
            console.print(f"  • {kind_badge} [bold]{sp.name}[/bold] ({format_duration(sp.duration_ms)})")
    console.print()


@app.command(name="scan")
def scan(
    path: str = typer.Argument(
        ".",
        help="Path to repository or directory to scan (defaults to current directory)",
    ),
    format: OutputFormat = typer.Option(
        OutputFormat.TABLE,
        "--format",
        "-f",
        help="Output format: table (rich interactive terminal), json (system manifest), or mermaid (diagram)",
    ),
    mermaid: bool = typer.Option(
        False,
        "--mermaid",
        help="Shortcut to output Mermaid diagram (equivalent to -f mermaid)",
    ),
    json_output_flag: bool = typer.Option(
        False,
        "--json",
        help="Shortcut to output Cohzen Manifest JSON (equivalent to -f json)",
    ),
    output: Optional[Path] = typer.Option(
        None,
        "--output",
        "-o",
        help="Write output to a specified file instead of stdout",
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="Display detailed debugging info during scan",
    ),
    view: bool = typer.Option(
        False,
        "--view",
        help="Open an interactive graphical visualizer in the default browser",
    ),
) -> None:
    """Scan a codebase to reconstruct LangGraph architecture and produce a system manifest."""
    if mermaid:
        format = OutputFormat.MERMAID
    elif json_output_flag:
        format = OutputFormat.JSON

    if format == OutputFormat.TABLE and not output and not view:
        with console.status(f"[bold cyan]Scanning repository for LangGraph architectures at {path}...[/bold cyan]"):
            result = scan_repository(path, verbose=verbose)
    else:
        result = scan_repository(path, verbose=verbose)

    if view:
        from cz.formatters.viewer import open_in_browser
        viewer_path = open_in_browser(result)
        console.print(f"[bold green]✔ Opened interactive architecture visualizer in browser ({viewer_path})[/bold green]")
        return

    # Format the result
    if format == OutputFormat.TABLE:
        if output:
            file_console = Console(record=True, width=120)
            print_console_report(result, console=file_console)
            output.write_text(file_console.export_text(), encoding="utf-8")
            console.print(f"[green]✔ Saved scan table report to {output}[/green]")
        else:
            print_console_report(result, console=console)

    elif format == OutputFormat.JSON:
        json_output = format_json(result)
        if output:
            output.write_text(json_output, encoding="utf-8")
            console.print(f"[green]✔ Saved JSON manifest to {output}[/green]")
        else:
            print(json_output)

    elif format == OutputFormat.MERMAID:
        mermaid_output = format_mermaid(result)
        if output:
            output.write_text(mermaid_output, encoding="utf-8")
            console.print(f"[green]✔ Saved Mermaid diagram to {output}[/green]")
        else:
            print(mermaid_output)


@app.command(name="audit")
def audit(
    path: str = typer.Argument(
        ".",
        help="Path to repository or directory to audit (defaults to current directory)",
    ),
    json_output_flag: bool = typer.Option(
        False,
        "--json",
        help="Output audit findings and coverage as JSON",
    ),
    output: Optional[Path] = typer.Option(
        None,
        "--output",
        "-o",
        help="Write output to a specified file instead of stdout",
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="Display detailed debugging info during scan",
    ),
) -> None:
    """Audit observability, tracing, and telemetry instrumentation across nodes and tools."""
    if not output and not json_output_flag:
        with console.status(f"[bold magenta]Auditing observability instrumentation at {path}...[/bold magenta]"):
            result = scan_repository(path, verbose=verbose)
    else:
        result = scan_repository(path, verbose=verbose)

    if json_output_flag:
        audit_json = result.observability.model_dump_json(indent=2) if result.observability else "{}"
        if output:
            output.write_text(audit_json, encoding="utf-8")
            console.print(f"[green]✔ Saved audit JSON to {output}[/green]")
        else:
            print(audit_json)
    else:
        if output:
            file_console = Console(record=True, width=120)
            print_audit_report(result, console=file_console)
            output.write_text(file_console.export_text(), encoding="utf-8")
            console.print(f"[green]✔ Saved audit report to {output}[/green]")
        else:
            print_audit_report(result, console=console)


@app.command(name="view")
def view_graph(
    path: str = typer.Argument(".", help="Path to repository or file to visualize"),
) -> None:
    """Scan and open an interactive graphical visualizer in your browser."""
    from cz.formatters.viewer import open_in_browser
    result = scan_repository(path)
    viewer_path = open_in_browser(result)
    console.print(f"[bold green]✔ Opened interactive architecture visualizer in browser ({viewer_path})[/bold green]")


@app.command(name="version")
def version() -> None:
    """Display the version of cz."""
    console.print(f"[bold cyan]cz[/bold cyan] version [green]{__version__}[/green]")


def main() -> None:
    """CLI entrypoint."""
    app()


if __name__ == "__main__":
    main()
